baseURL = "https://jtb324.github.io/"
languageCode = "en-us"
title = "My Portfolio"
theme = "hugo-profile"
publishDir = "docs"

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[pagination]
pagerSize = 3

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
title = "My Portfolio"
description = "Researcher and Developer Portfolio"
# staticPath must match your baseURL path for GitHub Pages and local preview with subdirectory
staticPath = ""
# favicon = "/fav.png"
useBootstrapCDN = false
animate = true
customCSS = true

[params.navbar]
align = "ms-auto"
brandName = "My Portfolio"
disableSearch = false
[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true
[params.navbar.menus]
disableAbout = false
disableExperience = false
disableEducation = false
disableProjects = false
disableAchievements = true
disableContact = false

[params.hero]
enable = true
intro = "Hi, my name is"
title = "James Baker"
subtitle = "PhD Candidate & Researcher"
content = "I am a PhD Graduate Student and software developer in Human Genetics. Welcome to my portfolio."
image = "/images/hero-man.svg"
[params.hero.bottomImage]
enable = true
[params.hero.button]
enable = true
name = "Download CV"
url = "files/James_Baker_CV.pdf"
download = true
newPage = false
[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/jtb324"
[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/james-baker-233243339"

[params.about]
enable = true
title = "About Me"
content = "I am a PhD student in the Human Genetics Program at Vanderbilt University. My research focuses on how we can leverage distant relatedness in large biobanks linked to electronic health data to explore the genetic causes of disease. To investigate this, I design workflows and software in (*mostly*) python and R for both local HPC environments and the cloud using Terra.bio. Additionally, I have an interest in how we can leverage modern high performance data science packages such as Polars and DuckDB to increase the scalability of many genomic workflows to accommodate the large biobanks such as BioVU, All of Us, and UK Biobank."

[params.skills]
enable = true
title = "Skills"
content = "Here are some of the technologies I work with:"
items = [
  "Python",
  "R",
  "Pandas",
  "Polars",
  "DuckDB",
  "ggplot",
  "SQL",
  "Docker",
  "Git & GitHub",
  "REGENIE",
  "SAIGE",
  "PLINK",
  "BCFtools",
]

[params.my_projects]
enable = true
title = "Software Projects"
[[params.my_projects.items]]
title = "DRIVE"
description = "Distant Relatedness for Identification and Variant Evaluation. A tool leveraging graph theory and identity-by-descent (IBD) in biobanks to identify networks of related individuals and evaluate genetic variants."
image = "/images/DRIVE_graphical_abstract_flowchart.png"
github = "https://github.com/belowlab/drive"
documentation = "https://drive-ibd.readthedocs.io/en/latest/"
contributions = [
  "Conceptual design and programmatic implementation",
  "Optimized memory usage and performance for large-scale biobank data with packages like duckdb and pandas",
  "Wrote comprehensive documentation available on both GitHub and Readthedocs.",
  "Integration tests as well as continuous integration through GitHub actions",
  "Performance testing and benchmarks using pytest",
  "Simulated test IBD data for integration tests and examples",
]

[[params.my_projects.items]]
title = "IBDMap"
description = "A computational workflow for identity-by-descent (IBD) mapping. IBDMap identifies genomic regions associated with disease by detecting excess IBD segment sharing among affected individuals in biobank-scale datasets."
image = "/images/IBDMap_flowchart.png"
github = "https://github.com/rjbohlender/IBDMap"
contributions = [
  "Restructured & refactored python IBDreduce code to PDM build system for reproducible installs",
  "Containerized application using a multi-stage docker build",
  "Tested the build and install pipelines for the c++ code and the python code",
]

[[params.my_projects.items]]
title = "COMPADRE"
description = "Combined pedigree-aware distant relatedness estimation for improved pedigree reconstruction. This tool leverages genome-wide IBD sharing to accurately reconstruct families even with sparse or ungenotyped individuals."
image = "/images/COMPADRE_flowchart_v2.png"
github = "https://github.com/jtb324/COMPADRE"
documentation = "https://jtb324.github.io/COMPADRE"
contributions = [
  "Tested the conda and docker installations",
  "Refactored communication between both the perl frontend and the python server to improve error handling and user experience",
]
[[params.my_projects.items]]
title = "Pubmed RAG"
description = "CLI TUI that allows the user to search for abstracts related to a topic of interest. Abstracts are retrieved from pubmed and then embedded with a vector database. Vector search is performed to find relevant abstracts and then an llm is used to summarize the abstracts and return results. This project uses common technologies like FastAPI, LangChain, HuggingFace (LLMs), Qdrant (for vector store), and Bubbletea (tui interface)."
image = "/images/pubmed_llm_rag_project.png"
github = "https://github.com/jtb324/pubmed_rag"


[params.experience]
enable = true
[[params.experience.items]]
company = "College of Basic Sciences - Vanderbilt University"
companyUrl = "https://www.vanderbilt.edu/"
mentors = "David Samuels, PhD & Jennifer Below, PhD"
[[params.experience.items.jobs]]
name = "Graduate Student Researcher"
date = "Aug 2019 - Present"
content = ""
projects = [
  "DRIVE: Python CLI tool leveraging graph theory and identity-by-descent (IBD) in biobanks to identify networks of related individuals",
  "IBDMap: A C++ and python tool testing genome-wide for enrichment of IBD sharing between pairs of cases and case-control pairs in a biobank",
  "COMPADRE: Perl and Python tool for Pedigree reconstruction and the identification of the maximum unrelated set",
]

[[params.experience.items]]
company = "Department of Chemistry: North Carolina State University"
companyUrl = "https://www.ncsu.edu/"
mentors = "Christian Melander, PhD"
[[params.experience.items.jobs]]
name = "Undergraduate Student Researcher"
date = "Aug 2018 - Aug 2019"
content = ""
projects = [
  "Meridianin D Analogues Display Antibiofilm Activity against MRSA and Increase Colistin Efficacy in Gram-Negative Bacteria",
]

[params.education]
enable = true
[[params.education.items]]
title = "PhD in human genetics"
school = { name = "Vanderbilt University", url = "https://www.vanderbilt.edu/" }
date = "Aug 2019 - present"
[[params.education.items]]
title = "B.S. in Chemistry"
school = { name = "North Carolina State University", url = "https://www.ncsu.edu/" }
date = "Aug 2014  - May 2018"
[[params.education.items]]
title = "B.S. in Biochemistry"
school = { name = "North Carolina State University", url = "https://www.ncsu.edu/" }
date = "Aug 2016  - May 2019"

[params.projects]
enable = true
title = "Publications"
[[params.projects.items]]
title = "Common variant approaches to study Mendelian disease gene function identify novel phenome and pathways associated with PLOD3"
authors = "Alexandra Scalici, James T Baker, Freida Blostein, Megan Shuey, Dharmendra Choudhary, Ela W Knapik, David C Samuels, Jennifer E Below, Lisa Bastarache, Tyne W Miller-Fleming, Nancy J Cox"
content = "MedRxiv 2025"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1101/2025.11.25.25340832"

[[params.projects.items]]
title = "Genome sequencing of 35,024 predominantly African ancestry persons addresses gaps in genomics and healthcare"
authors = "Cecile Avery, Mojgan Babanejad, James Baker, Xavier Bledsoe, Freida Blostein, Robert W Corty, Kimberlyn Ellis, Adriana M Hung, Allison Lake, John Shelley, Quanhu Sheng, Vanderbilt University Medical Center and Alliance for Genomic Discovery Investigators, Melinda Aldrich, Melissa Basford, Lisa Bastarache, Jennifer Below, Alexander G Bick, Peter Embi, QiPing Feng, Eric Gamazon, Lide Han, Jibril Hirbo, Kayla Marginean, Jonathan Mosley, Jill Pulley, Dan M. Roden, Douglas M Ruderfer, Megan Shuey, Yu Shyr, C Michael Stein, Colin Walsh, Consuelo Wilkins"
content = "MedRxiv 2025"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1101/2025.10.30.25338549"


[[params.projects.items]]
title = "COMPADRE: Combined pedigree-aware distant relatedness estimation for improved pedigree reconstruction"
authors = "Evans GF, Baker JT, Petty LE, Petty AS, Polikowsky HG, Bohlender RJ, Chen HH, Chou CY, Viljoen KZ, Beilby JM, Kraft SJ, Zhu W, Landman JM, Morrow AR, Bian D, Scartozzi AC, Huff CD, Below JE"
content = "American Journal of Human Genetics, 2025"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1016/j.ajhg.2025.09.011"

[[params.projects.items]]
title = "Genetic study of von Willebrand factor antigen levels â‰¤ 50 IU/dL identifies variants associated with increased risk of VWD and bleeding"
authors = "Friedman RK, Heath AS, Huffman JE, Baker JT, Hasbani NR, Gagliano Taliun SA, Chen MH, Howard TE, Lewis JP, Pankratz N, Patil S, Reiner AP, Thibord F, Yanek LR, Yao J, Chen HH, Curran JE, Faraday N, Guo X, Wheeler MM, Ryan KA, Zhou X, Cho K, Almasy L, Auer PL, Becker LC, Wilson PWF, Boerwinkle E, O'Connell JR, Rich SS, Samuels DC; NHLBI Trans-Omics for Precision Medicine (TOPMed) Consortium; TOPMed Hematology & Hemostasis Working Group; VA Million Veteran Program; Blangero J, Fornage M, Kooperberg C, Mathias RA, Mitchell BD, Rotter JI, Johnson AD, Smith NL, Coban-Akdemir ZH, Below JE, Morrison AC, Johnsen JM, de Vries PS"
content = "Journal of Thrombosis and Haemostasis"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1016/j.jtha.2025.04.029"

[[params.projects.items]]
title = "Gene and phenome-based analysis of the shared genetic architecture of eye diseases"
authors = "Scalici A, Miller-Fleming TW, Shuey MM, Baker JT, Betti M, Hirbo J, Knapik EW, Cox NJ"
content = "American Journal of Human Genetics (2025)"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1016/j.ajhg.2025.01.004"

[[params.projects.items]]
title = "Detection of distant relatedness in biobanks to identify undiagnosed cases of Mendelian disease as applied to Long QT syndrome"
authors = "Lancaster MC, Chen HH, Shoemaker MB, Fleming MR, Strickland TL, Baker JT, Evans GF, Polikowsky HG, Samuels DC, Huff CD, Roden DM, Below JE"
content = "Nature Communications (2025)"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1038/s41467-024-51977-4"


[[params.projects.items]]
title = "Machine-learning based classification of Frontotemporal dementia in electronic health records for genetic discovery"
authors = "Below, J., Shaw, D., Evans, G., Baker, J., Bohlender, R., Petty, A., Petty, L., Roshani, R., Lifferth, J., Bastarache, L., Naj, A., Bush, W., Darby, R., McMillan, C., Samuels, D., Huff, C"
content = "Alzheimer's & Dementia (2023)"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1002/alz.080074"


[[params.projects.items]]
title = "2-aminobenzimidazoles as antibiofilm agents against salmonella enterica serovar typhimurium"
authors = "Huggins, W. M., Vu Nguyen, T., Hahn, N. A., Baker, J.T., Kuo, L. G., Kaur, D., Melander, R. J., Gunn, J. S., & Melander, C"
content = "MedChemComm (2018)"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1039/c8md00298c"

[[params.projects.items]]
title = "Meridianin D analogues display antibiofilm activity against MRSA and increase colistin efficacy in gram-negative bacteria"
authors = "Huggins, W. M., Barker, W. T., Baker, J.T., Hahn, N. A., Melander, R. J., & Melander, C"
content = "ACS Medicinal Chemistry Letters"
[params.projects.items.featured]
name = "Link"
link = "https://doi.org/10.1021/acsmedchemlett.8b00161"

[params.contact]
enable = true
content = "Feel free to reach out directly via email:"
btnName = "james.baker@vanderbilt.edu"
btnLink = "mailto:james.baker@vanderbilt.edu"
# [params.contact.formspree]
#   enable = true
#   formId = "yourid"

[params.footer]
[params.footer.socialNetworks]
github = "https://github.com/jtb324"
linkedin = "https://www.linkedin.com/in/james-baker-233243339"

[menu]
[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/#projects"
weight = 1
